### ISSUE TITLE
[Bug]: Duplication files

### ISSUE THREAD

**Issue by Alex-Prevot** [PoCInnovation/InterPlanetaryCloud#63]
### Description

With Leo we were working on IPComputing we noticed a bug when changing route.

### What happened?

With Leo we were working on IPComputing we noticed a bug when changing route I explain, we created a button to go on the IPComputing route (a private route) and when we returned to the IPCloud page the upload files this duplicated not only on the front but also on the aleph nodes. (several post message seen on explorer d'aleph) 

### Expected behaviour

Files duplication.

### Environment

- Linux
- Computing branch / Master if you change a little bit code.

### Steps to reproduce

For reproduce the bug:
```	
import { Link as RouteLink } from 'react-router-dom';

import { Button, Link } from '@chakra-ui/react';

<>
	<Link as={RouteLink} to="/computing" w="100%" id="ipc-homeView-login-button">
		<Button variant="inline" w="100%" mb="16px" id="ipc-dashboardView-upload-file-modal-button">
			Inter Planetary Computing
		</Button>
	</Link>
</>
```
You can add this button on sideBar.tsx at the end.

Don't forget add in Routes.tsx this ->

```  
import ComputingView from 'views/ComputingView';

<PrivateRoute path="/computing" children={<ComputingView />} />
```

you can create a ComputingView.tsx and add the same button don't forget change redirection.

```
import { Link as RouteLink } from 'react-router-dom';

import { Button, Link } from '@chakra-ui/react';

<Link as={RouteLink} to="/dashboard" w="100%" id="ipc-homeView-login-button">
	<Button variant="inline" w="100%" mb="16px" id="ipc-dashboardView-upload-file-modal-button">
		Inter Planetary Cloud
	</Button>
</Link>
```
Click on this button and admired the result :)

---

![ipcBUG](https://user-images.githubusercontent.com/72015142/172070508-08e1ee64-ae20-49df-a795-28e32322219d.png)
![image](https://user-images.githubusercontent.com/72015142/172070493-5230857c-9c4f-4896-b55c-3ad436edc7f3.png)

![image](https://user-images.githubusercontent.com/72015142/172070611-5b06be51-e363-45a8-b4d6-0cc3866135a2.png)

### Relevant log output

```C++
you can see behavior these images, duplication is real.
```

### Proposed solution

/

**Comment by lucas-louis** [comment]
It seems, that there is no bug, I mean on aleph.
It's true that there is a bug with the display, but on the explorer, there is no duplication.

I tried on the `master` branch with the latest version and I have this on the explorer:

![Screenshot from 2022-06-05 23-32-34](https://user-images.githubusercontent.com/72020723/172071555-3bb2781d-89a0-43b5-8199-e8bb91678987.png)

Two possibilities:
- The first one:
  - There is no bug, to be sure you need to check the content of the duplicate `post` messages on the explorer.
  - If it's all the same, that's normal. It means that somewhere in the code, the `post` message is updated with the same content.
  - If it's not the same, you need to check if there are many `store` messages in the explorer. I think that it's not that, in your screenshot we see only one `store` message, but check it just to be sure.
- The second one:
  - There is a bug, but not on the master branch, on your branch. I can't try by myself on your branch because it seems that you haven't pushed your last changement

**For me** it's a problem with your code on your branch, but I don't think it's a real duplication bug, in fact, only the `post` message is *duplicate* but not the `store` message.
So somewhere in your code, there is a loop which adds the same file on your `post` message, this is why you have many `amend` on the  `post` message. **BUT** it's not a bug in the production version.

**To fix it**:
- Try to debug the behaviour of IPC from the start to the end of the app
- Try to remove your new features, maybe it comes from that

:question: Have you tried on the master branch? Maybe my trying was not correctly done.

:information_source: Even if you fix this bug, there still one with the front.
The bug comes from the fact that when you go on the `dashboard` view, all the files are loaded, but the files already loaded before you click the button are not unloaded.
So there is a duplication, but if you refresh the page, everything returned to normal.

:warning: Fix this bug before merging your branch on the `dev` one.

**Comment by lucas-louis** [comment]
@ZerLock 

Yes like I said before, the graphic bug comes from the reload of the files/ contacts without unloading the old data so the data is duplicated.
> :information_source: Even if you fix this bug, there still one with the front.
The bug comes from the fact that when you go on the dashboard view, all the files are loaded, but the files already loaded before you click the button are not unloaded.
So there is a duplication, but if you refresh the page, everything returned to normal.

A quick and easy fix, will be to unload the old data (by clearing the array of files/ contacts) and load the new data.
